---
- name: Collect facts
  setup:
    gather_subset:
      - 'all'

- name: Update system
  become: true
  apt:
    update_cache: yes 
    force_apt_get: yes 
    cache_valid_time: 3600

- name: Upgrade all packages
  become: true
  apt: 
    upgrade: dist 
    force_apt_get: yes




