- name: Copy project to VM
  copy:
    src: ../../../app/consumer
    dest: "{{ home_directory }}"

- name: Build Consumer application 
  shell: go build .
  args:
    chdir: consumer/

- name: Check running process
  shell: echo -n $(pgrep consumer)
  register: check_process

# run if not running
- name: Run Consumer
  shell: "nohup ./consumer/consumer </dev/null >/dev/null 2>&1 &"
  when: check_process.stdout == ""




