---
- name: Start grafana
  systemd:
    name: grafana-server
    state: started

- name: restart_grafana
  systemd:
    name: grafana-server
    state: restarted

- name: Enable grafana
  systemd:
    name: grafana-server
    enabled: yes

